DEBUG = False
STRICTER = DEBUG
MAX_LINE_LENGTH = 8002  # 8k + '\r\n'
BUFFER_SIZE = 1 << 15
assert MAX_LINE_LENGTH * 2 < BUFFER_SIZE
ORIGIN = b"minhttp/0.1a"
TIMEOUT_PROCESS = 300 if DEBUG else 60
TRACE_METHOD_ENABLED = True
